# Generated by Django 2.2 on 2019-04-11 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investigadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigador',
            options={'verbose_name_plural': 'Investigadores'},
        ),
    ]
