# Generated by Django 2.2 on 2019-05-01 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Investigadores', '0002_auto_20190411_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='usuario',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
