# Generated by Django 2.2 on 2019-04-11 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Investigadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Metadato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_de_necesidad_de_informacion', models.CharField(max_length=500)),
                ('cadena_de_busqueda', models.CharField(max_length=200)),
                ('prueba_piloto', models.BooleanField(default=False)),
                ('bibliotecas', models.ManyToManyField(to='Revisiones.Biblioteca')),
                ('investigadores', models.ManyToManyField(to='Investigadores.Investigador')),
                ('metadatos', models.ManyToManyField(to='Revisiones.Metadato')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaDeInvestigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=150)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Revisiones.Revision')),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IN', 'inclusion'), ('EX', 'exclusion'), ('CA', 'calidad')], default='inclusion', max_length=2)),
                ('descripcion', models.CharField(max_length=200)),
                ('revison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Revisiones.Revision')),
            ],
        ),
    ]
