# Generated by Django 2.2 on 2019-04-11 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Revisiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biblioteca',
            options={'verbose_name_plural': 'bibliotecas'},
        ),
        migrations.AlterModelOptions(
            name='criterio',
            options={'verbose_name_plural': 'Criterios'},
        ),
        migrations.AlterModelOptions(
            name='metadato',
            options={'verbose_name_plural': 'metadatos'},
        ),
        migrations.AlterModelOptions(
            name='revision',
            options={'verbose_name_plural': 'revisiones'},
        ),
        migrations.AddField(
            model_name='revision',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
