# Generated by Django 2.2 on 2019-05-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revisiones', '0002_auto_20190411_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntadeinvestigacion',
            options={'verbose_name_plural': 'preguntas de investigacion'},
        ),
        migrations.AlterField(
            model_name='revision',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='prueba_piloto',
            field=models.BooleanField(default=False, verbose_name='¿Se realizara prueba piloto?'),
        ),
    ]
