# Generated by Django 2.2 on 2019-06-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revisiones', '0005_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='formulario_de_extraccion',
            field=models.FileField(default=0, upload_to='formularios_de_extraccion/'),
            preserve_default=False,
        ),
    ]
