# Generated by Django 2.2 on 2019-06-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Revisiones', '0006_articulo_formulario_de_extraccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'verbose_name_plural': 'Articulos'},
        ),
        migrations.RenameField(
            model_name='criterio',
            old_name='revison',
            new_name='revision',
        ),
    ]
