# Generated by Django 2.2 on 2019-06-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revisiones', '0007_auto_20190625_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='estado',
            field=models.CharField(choices=[('A1', 'Actividad 1'), ('A2', 'Actividad 2'), ('A3', 'Actividad 3')], default='Actividad 1', max_length=2),
        ),
    ]
