# Generated by Django 2.2 on 2019-10-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revisiones', '0009_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='formulario_generico',
            field=models.BooleanField(default=False, verbose_name='¿Se creo un formulario de extraccion de datos?'),
        ),
    ]
